### ISSUE TITLE
Code breaking on Mac when running main.py

### ISSUE THREAD

**Issue by SippinOnJuiceBox** [CarletonURocketry/ground-station#10]
Code breaks on mac when running main.py
Current fix: comment out lines 125 and 126 in `/modules/serial/serial_manager.py`
Not sure why its breaking though, its probably a piece of code from an older version

**Comment by TASelwyn** [comment]
Try using linux :)

**Comment by SippinOnJuiceBox** [comment]
linux is for nerds 🤓
