### ISSUE TITLE
[ENHANCEMENT] Implement Altitude Data Block

### ISSUE THREAD

**Issue by linguini1** [CarletonURocketry/ground-station#46]
## Problem
Packet encoding broke. We need to write decoding for altitude data blocks.

## Proposed Solution
See stub in `modules/telemetry/v1/data_block.py`

**Comment by matt-bekkers** [comment]
I'm confused as to how to link a branch to this, it should just be the altitude-db one but it's closed?

**Comment by TASelwyn** [comment]
@matt-bekkers I believe it's because packets-v1 is still a branch, so you should be PRing to that branch and not main.

**Comment by linguini1** [comment]
This was completed anyways!
