### ISSUE TITLE
[BUG] telementry_utils.py and parse_radio_block function.

### ISSUE THREAD

**Issue by Juan-789** [CarletonURocketry/ground-station#84]
When inputting a block header with a block subtype that its recognized by DataBlockSubtype yet not implemented, e.g.
![image](https://github.com/CarletonURocketry/ground-station/assets/79994699/141246b0-5280-47ed-80d6-110df114fb26)

It should raise NotImplementedError
![image](https://github.com/CarletonURocketry/ground-station/assets/79994699/9b1cadc8-73d0-4d81-a9b9-f1b9a774d3f3)
 yet it raises at v1/data_block.DataBlock.parse the DataBlockUnknownException 
![image](https://github.com/CarletonURocketry/ground-station/assets/79994699/0f217993-04e7-44b0-9120-0dae8f2449f6)

when it should go to the parse_data_block
![image](https://github.com/CarletonURocketry/ground-station/assets/79994699/959b59a1-ddc6-4a34-9d02-9aeef0fa9ecc)

**Comment by Juan-789** [comment]
With further investigation found out maybe I need to create DataBlocks for the remaining block subtypes or could do a work around just to raise the proper NotImplemented Error @linguini1

**Comment by linguini1** [comment]
> With further investigation found out maybe I need to create DataBlocks for the remaining block subtypes or could do a work around just to raise the proper NotImplemented Error @linguini1

Tbh just toss the raise `DataBlockUnknownException` and replace with `NotImplemented`. See my comment on PR #89.
