### ISSUE TITLE
Packet header fields

### ISSUE THREAD

**Issue by linguini1** [CarletonURocketry/ground-station#86]
In [modules/telemetry/v1/block.py](https://github.com/CarletonURocketry/ground-station/blob/main/modules/telemetry/v1/block.py), the `version` and `src_addr` fields in `PacketHeader` should be constructed using the enums for packet versions and device addresses.

This will validate fields instead of having plain integers which could contain erroneous values (1000 for source address).

As always, tests may need to be updated to reflect this changes.

**Comment by EliasJRH** [comment]
Packet header field versions will be checked against the range of valid versions in [this pr](https://github.com/CarletonURocketry/ground-station/pull/90). We also don't currently use src_addr anywhere, should it even be kept?

**Comment by linguini1** [comment]
> Packet header field versions will be checked against the range of valid versions in [this pr](https://github.com/CarletonURocketry/ground-station/pull/90). We also don't currently use src_addr anywhere, should it even be kept?

Source address must be kept since it is a packet field.
